#ifndef SALEAESOCKETAPI_GLOBAL_H
#define SALEAESOCKETAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SALEAESOCKETAPI_LIBRARY)
#  define SALEAESOCKETAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SALEAESOCKETAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SALEAESOCKETAPI_GLOBAL_H
